### ISSUE TITLE
Chart Calculation Inconsistencies

### ISSUE THREAD

**Issue by minniear** [sfanous/cantrill.io-courses-scraper#1] opened 2021-10-24 01:24 UTC
When using the chart tab, the overlap time doesn't match when you interchange classes for first two fields. If you choose one class for the first section (Ex: SAA-CO2) and a different one for the second section (DVA-CO1) and choose All Lectures for the third, the total shared time is 36:34:03. when you switch those choices so that DVA-CO1 is chosen for the first section and SAA-CO2 is chosen for the second the total shared time is 40:03:33. All the other values are off by a similar percentage within the venn diagram. The "Across" does not matter either. 

This is present for every option available.

**Comment by sherif-fanous** [comment] 2021-10-24 02:06
Hey @minniear

Thanks for reporting the issue. I'll have a closer look when I have time and I think I know the culprit in both cases.

With regards to the large discrepancy with SAA-C02 that is attributed to lectures tagged as `SAAC02SHARED`. I think I can do a better job handling these as right now it seems they are counted from the perspective of the other course only.

With regards to the minor discrepancy my hunch (although I need to take a closer look) is because of the fuzzy matching logic involved to match lectures. This algorithm tries to match lectures as long as the name matches at around 95% and the duration delta is not more than 5%. Now because the duration can differ slightly although the lecture is identical the intersection duration will have a different value depending on which course was used to determine the overlap.

**Comment by sherif-fanous** [comment] 2021-10-24 19:52
Ok, so I confirmed the minor discrepancy issue is exactly what I expected.

The code perform some fuzzy matching. So here's an example

SAA-C02 course has a lecture titled `Simple Storage Service (S3) Basics (15:58)`
DVA-C01 course has a lectured titled `[SAAC02SHARED] Simple Storage Service (S3) Basics (15:48)`

These 2 lectures are identical, but for some reason one of them has a duration of 15:58 while the other has a duration of 15:48.

So the code marks them as shared but when the chart is created the intersection is created based on the content of the right hand side course in the Venn diagram, so if you compare SAA-C02 to DVA-C01 then 15:48 will be counted as shared, however if you flip the chart around then 15:58 will be counted as shared.

The impact of this issue is minimal yet I think I can easily fix it by introducing some logic to always use a specific course to calculate the intersection (e.g. Always use the course with the lower lexicographic order of the code, so in the case above always use DVA-C01)

I'm still looking into the large discrepancy with regards to SAA-C02.

**Comment by sherif-fanous** [comment] 2021-11-07 20:09
Fixed in https://github.com/sfanous/cantrill.io-courses-scraper/commit/1e05d174d9b601724a6c0c8df182119fdb8ced5d

**Closed as completed** 2021-11-07 20:09 UTC
